version: '3'
services:
  app:
    container_name: gitops
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    networks:
      - gitops
    volumes:
      - .:/go/src/gitops

networks:
  gitops:
    driver: bridge
