name: CD Gitops

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/gitops
        tags: ${{github.sha}}, latest